### PR TITLE
Remove sized bounds where appropriate

### LINKED ISSUE #99: Accept dynamically sized Read, Write, and Serialize implementations
See https://github.com/TyOverby/bincode/pull/95#issuecomment-276464744.

Sure! Accepting a ?Sized type parameter for io::Read and io::Write means that it will work with &mut io::Read and &mut io::Write trait objects which are dynamically sized.

```rust
use std::fs::File;
use std::io::Read;

fn main() {
    let mut data = File::open("important.bin").unwrap();
    let trait_object: &mut Read = &mut data;
    deserialize_from(trait_object); // requires ?Sized
}

fn deserialize_from<R>(_: &mut R) where R: Read {}
```
And accepting a ?Sized type parameter for &T means that it can work with dynamically sized implementations of Serialize, which includes str and [T] among others.

```rust
fn main() {
    serialize("&str"); // requires ?Sized
}

trait Serialize {}
impl Serialize for str {}

fn serialize<T>(_: &T) where T: Serialize {}
```

### PR DESCRIPTION
**Pull request by dgriffen**
Closes #99

### CODE REVIEW

**Comment by TyOverby** [comment]
On the stable compiler, you still need to have the `: ?Sized` inside of the `<..>` for the function (it can't be in the `where` clause)

**Comment by TyOverby** [comment]
Also, I'd like to point out that you beat me to this PR by 3 minutes 
💯 :100:

**Comment by dgriffen** [comment]
I'm at dinner right now. I'll fix after.

**Comment by TyOverby** [comment]
Looks good!

**Pull request merged**
