### PR TITLE
Update to serde 1.0 branch

### PR DESCRIPTION
**Pull request by dtolnay**
### TODO:

- [ ] Support deserializing borrowed data.

### CODE REVIEW

**Comment by TyOverby** [comment]
Ah!  You beat me to it!  I got about half of this done over the weekend, so I'm super happy that you finished up!

According to bincode_bench, this upgrade is faster too!

**Comment by TyOverby** [comment]
Btw, Servo is planning on adding support for bincode in webrender here: https://github.com/servo/webrender/pull/1124#issuecomment-294602251

They're concerned about deserializing perf, so I was wondering if you had some insight into why deserializing seems to be a lot more costly than serializing.  Their structures seem to be mostly structs and enums, and I was wondering if there is anything we could do to speed it up?

**Comment by dtolnay** [comment]
@TyOverby I'll leave the zero-copy refactor to you.

**Comment by TyOverby** [comment]
@dtolnay Sounds good.  Merge now, zero copy later?

**Comment by dtolnay** [comment]
Sure, just make sure not to publish it until then. Maybe stick a `publish = false` in Cargo.toml.

**Comment by TyOverby** [comment]
👍

**Comment by TyOverby** [comment]
added `publish=false`

**Pull request merged**
