### PR TITLE
Update to serde 0.8.0

### PR DESCRIPTION
**Pull request by dtolnay**
Supersedes #83.

### CODE REVIEW

**Comment by TyOverby** [comment]
Does this serde update include any changes that would change the ordering of bytes produced by bincode?

**Comment by dtolnay** [comment]
No. There are 3 user-facing changes but all are in deserialization:

- `deserialize_str` used to not be implemented, meaning it forwarded to `deserialize` and failed. Now it is implemented to deserialize a `&str`. This affects only Deserialize types that used to fail and now succeed.
- `deserialize_struct_field` fails with a better message.
- `deserialize_ignored_any` fails with a better message.

As an incentive, I suspect you will see a nice performance improvement in serialization for both structs and vectors.

I can put together a test suite this weekend before you release to prove the bytes are the same.

**Comment by TyOverby** [comment]
Sounds good.  I was only asking because I wanted to know if I'd need to bump the version number.  However, I'm pretty sure I need to bump the version anyway, simply because it's re-exporting serde which bumped to 0.8.0.

The test suite already makes sure that the `rustc-serialize` encoding is the same (byte for byte) as the `serde` encoding, so I'm not super worried.

Thanks for the contribution!

**Comment by TyOverby** [comment]
Published to crates.io as 0.6.0

**Pull request merged**
